CREATE DATABASE IF NOT EXISTS test_db DEFAULT CHARACTER SET UTF8;
USE test_db;
DROP TABLE users;
CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	pass VARCHAR(100) NOT NULL,
	CONSTRAINT PK_users PRIMARY KEY(id)
);
INSERT INTO users(username, pass) VALUES
	('fulanito', 'fulanito123');